# Generated by Django 4.2.3 on 2023-07-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
